<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIGBRHET\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIGBRHET/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIGBRHET.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIGBRHET\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIGBRHET\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IGBRHET',
    'container.build_id' => '8568801d',
    'container.build_time' => 1606994787,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIGBRHET');
