<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerU8szHQM\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerU8szHQM/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerU8szHQM.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerU8szHQM\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerU8szHQM\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'U8szHQM',
    'container.build_id' => 'a407728a',
    'container.build_time' => 1608185552,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerU8szHQM');
