<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRpBwG1L\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRpBwG1L/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRpBwG1L.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRpBwG1L\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRpBwG1L\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RpBwG1L',
    'container.build_id' => 'e4235a26',
    'container.build_time' => 1608139639,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRpBwG1L');
